homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 61.037724
  longitude: 28.093313
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 105
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki


  customize:
    light.keittio_katto_11:
      hidden: true
    light.keittio_katto_12:
      hidden: true
    light.keittio_katto_13:
      hidden: true
    light.keittio_katto_14:
      hidden: true
    light.keittio_katto_21:
      hidden: true
    light.keittio_katto_22:
      hidden: true
    light.keittio_katto_23:
      hidden: true
    light.keittio_katto_24:
      hidden: true
    light.ruokapoyta_2:
      hidden: true
    light.ruokapoyta_3:
      hidden: true
    light.keittio_spotit:
      friendly_name: Keittiön spotit
    light.keittio_ruokapoyta:
      friendly_name: Ruokapöytä
    device_tracker.iphone:
      friendly_name: Mikko

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  # Mikko 20.12. Fix for Macbook Pro Safari not loading on HA voice0.60 issue
  javascript_version: es5
  
# Enables configuration UI
config:

logger:
  #default: debug
  default: warning
  #logs:
  #  homeassistant.components.mqtt: debug

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#tradfri:
#  host: 192.168.1.52
#  api_key: 6mHP77iZGE8cOBSx
#  allow_tradfri_groups: true

# IOS
ios:

mqtt:
  broker: 192.168.1.99
  protocol: 3.1

light:
  - platform: mqtt_json
    name: "WC LED"
    state_topic: "MyHome/Toilet/stat/multisensor"
    command_topic: "MyHome/Toilet/tele/multisensor"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  # Example configuration.yml entry
  - platform: mqtt
    name: "Quinled PWM 1"
    state_topic: "MyHome/dimmers/stat/quinled_pwm_dimmer_1/RESULT"
    #state_value_template: >
    #  {% if value_json.PWM.PWM1 > 0 %}
    #    {{ value_json.svalue5 }}
    #  {% endif %}
    #  {% if ({{ value_json.PWM.PWM1 }} > 0) %}
    #    ON
    #  {% else %}
    #    OFF
    #  {% endif %}
    #payload_on: "ON"
    payload_off: "0"
    state_value_template: "{{ value_json.PWM.PWM1 }}"
    command_topic: "MyHome/dimmers/cmnd/quinled_pwm_dimmer_1/PWM1"
    brightness_state_topic: "MyHome/dimmers/stat/quinled_pwm_dimmer_1/RESULT"
    brightness_command_topic: "MyHome/dimmers/cmnd/quinled_pwm_dimmer_1/PWM1"
    brightness_value_template: "{{ value_json.PWM.PWM1 }}"
    on_command_type: "brightness"
    brightness_scale: 900
    availability_topic: "MyHome/dimmers/stat/quinled_pwm_dimmer_1/LWT"
    #payload_on: "ON"
    #payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
    retain: false


# Weather prediction
sensor:
  - platform: yr
  - platform: mqtt
    name: "Autotalli lämpö"
    state_topic: "MyHome/Garage/Sensor1/Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Autotalli kosteus"
    state_topic: "MyHome/Garage/Sensor1/Humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Keittio"
    state_topic: "MyHome/Kitchen/Sensor1/Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Makuuhuone"
    state_topic: "MyHome/Bedroom/Sensor1/Temperature"
    unit_of_measurement: "°C"
#  - platform: mqtt
#    name: "Olohuone"
#    state_topic: "MyHome/LivingRoom/Sensor1/Humidity"
#    unit_of_measurement: "%"
  - platform: mqtt
    name: "Olohuone"
    state_topic: "MyHome/LivingRoom/Sensor1/Lightness"
    unit_of_measurement: "LUX"
#  - platform: mqtt
#    name: "Olohuone"
#    state_topic: "MyHome/LivingRoom/Sensor1/Temperature"
#    unit_of_measurement: "°C"
  - platform: mqtt
    name: "MH Janna"
    state_topic: "MyHome/BedroomJanna/Sensor1/Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Varasto"
    state_topic: "MyHome/StorageRoom/Sensor1/Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Kylpyhuone lämpö"
    state_topic: "MyHome/Bathroom/Sensor1/Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Kylpyhuone kosteus"
    state_topic: "MyHome/Bathroom/Sensor1/Humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Sähkö_W"
    state_topic: "MyHome/Consumption/tele/electricity/current_cons"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Sähkö_Wh"
    state_topic: "MyHome/Consumption/tele/electricity/Wh_counter"
    unit_of_measurement: "Wh"
  - platform: mqtt
    state_topic: "MyHome/Toilet/stat/multisensor"
    name: "WC Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "MyHome/Toilet/stat/multisensor"
    name: "WC LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'
  - platform: mqtt
    state_topic: "MyHome/Toilet/stat/multisensor"
    name: "WC Temperature"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "MyHome/Toilet/stat/multisensor"
    name: "WC Real Feel"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

binary_sensor:
  - platform: mqtt
    state_topic: "MyHome/Toilet/stat/multisensor"
    name: "WC PIR"
    payload_off: "standby"
    payload_on: "motion detected"
    value_template: '{{ value_json.motion }}'
    device_class: motion

switch:
  - platform: mqtt
    name: "Bathroom Sonoff1 Switch"
    state_topic: "MyHome/Bathroom/stat/sonoff_basic_1/POWER"
    command_topic: "MyHome/Bathroom/cmnd/sonoff_basic_1/POWER"
    availability_topic: "MyHome/Bathroom/tele/sonoff_basic_1/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
    retain: false


# Text to speech
#tts:
#  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#media_player:
#  - platform: panasonic_viera
#    host: 192.168.1.76
